language: python
python:
  - "2.7"
install:
- pip install -rtests/requirements.txt
- pip install .
script: python setup.py nosetests && tox
after_success: coveralls
notifications:
  slack: cocaine:qDewv6ZVDt0TciQeNdE47GqG
branches:
  only:
    - master
    - v0.11
