language: python
python:
  - "2.7"
before_install:
  - "ci/travis.sh"
install:
  - "pip install tox flake8"
script: tox && python setup.py nosetests
notifications:
  slack: cocaine:qDewv6ZVDt0TciQeNdE47GqG
branches:
  only:
    - master
    - v0.11
